### ISSUE TITLE
设置在播放网络视频时我增加了loading时就发出play状态unknown事件

### ISSUE THREAD

**Issue by zszen** [newyjp/JPVideoPlayer#101]
step1:
把`[JPVideoPlayerPlayVideoTool sharedTool].delegate = self;`
移动到上面的代码移到` [self progressRefreshWithURL:targetURL options:options receiveSize:storedSize exceptSize:expectedSize]; `上面

step2:
在
`- (nullable JPVideoPlayerPlayVideoToolItem *)playExistedVideoWithURL:(NSURL * _Nullable)url fullVideoCachePath:(NSString * _Nullable)fullVideoCachePath options:(JPVideoPlayerOptions)options showOnView:(UIView * _Nullable)showView playingProgress:(JPVideoPlayerPlayVideoToolPlayingProgressBlock _Nullable )progress error:(nullable JPVideoPlayerPlayVideoToolErrorBlock)error{`
  和
`- (nullable JPVideoPlayerPlayVideoToolItem *)playVideoWithURL:(NSURL * _Nullable)url tempVideoCachePath:(NSString * _Nullable)tempVideoCachePath options:(JPVideoPlayerOptions)options videoFileExceptSize:(NSUInteger)exceptSize videoFileReceivedSize:(NSUInteger)receivedSize showOnView:(UIView * _Nullable)showView playingProgress:(JPVideoPlayerPlayVideoToolPlayingProgressBlock _Nullable )progress error:(nullable JPVideoPlayerPlayVideoToolErrorBlock)error{`
开头都加上
```
if (self.delegate && [self.delegate respondsToSelector:@selector(playVideoTool:playingStatuDidChanged:)]) {
		[self.delegate playVideoTool:self playingStatuDidChanged:JPVideoPlayerPlayingStatusUnkown];
	}
```
这样就可以了

**Comment by newyjp** [comment]
Try version 3.0 please.
