### ISSUE TITLE
在慢速网站上会出现问题

### ISSUE THREAD

**Issue by zszen** [newyjp/JPVideoPlayer#102]
也许是加载当前段落时间过长, 也许是网站不支持分成不同部分下载(不太懂这个地方), 体现在有些视频(比较短)必须加载完毕才能正常播放(已经playing状态但是黑屏)然后下载完毕后要等很久, 大概是视频黑屏下运行了一遍一样. 另一种是视频长一点点, 但也就几十秒, 整个过程就直接黑屏, 即便下载完毕等很久也黑屏, 然后退出去再进去看加载本地缓存时都能正常播放

**Comment by weidongliu** [comment]
@zszen 这个库使用的边下边播方法会存在有这种问题，在网上看到说是解决不了。。。

**Comment by newyjp** [comment]
我也一直致力于找解决办法, 从我现在看过的资料来看, 没法在 AVPlayer 实现正真的边下载边播放, 但是不排除 FFmpeg 可以, 接下来我会去尝试使用 FFmpeg, 如果 OK 了, 就写 3.0 版本.

**Comment by newyjp** [comment]
Try version 3.0 please.
