### ISSUE TITLE
newyjp: 某些视频不能边下边播的同学请看这里 !!!

### ISSUE THREAD

**Issue by newyjp** [newyjp/JPVideoPlayer#104]
1. 坑主也一直致力于找解决办法, 从我现在看过的资料来看, 没法在 AVPlayer 实现正真的边下载边播放, 但是不排除 FFmpeg 可以, 接下来我会去尝试使用 FFmpeg, 如果 OK 了, 就会写 3.0 版本.

2. 还有有些童鞋说的拖动进度条, 当前使用 AVPlayer 都实现不了.

**Comment by madongdong5550422** [comment]
其实是可以边下边播的，只是有些url播放时，avplayer会先请求后面的一部分数据，导致一直下载不进行播放。针对这种情况处理一下，重新确定下载区间，就可以解决这个问题。

**Comment by newyjp** [comment]
请具体说一下你的思路 @madongdong5550422

**Comment by madongdong5550422** [comment]
思路其实还是挺简单的，就是根据avplayer请求数据range来下载，返给avplayer来实现播放，而不是定死从头开始下。最后根据每个range下载完的数据按正确的顺序拼出完整视频。

**Comment by madongdong5550422** [comment]
我重点没关注怎么拼出完整视频，我主要想对视频进行预加载。可能代码实现要考虑的东西挺多的

**Comment by vieriwml** [comment]
@madongdong5550422 你的思路还是不能边下边播啊，目前我们在实际的操作测试中也发现了AVPlayer对部分url播放的时候资源请求不是顺序而且混乱的问题，你的思路要让每个range下载完成了拼接，其实也是要等视频下载完成了才能判断能否成功拼接和播放，感觉还是不大对, 这个AVPlayer略坑啊。

**Comment by madongdong5550422** [comment]
这样做，不需等下载完成就可以播放，还可以实现对播放的快进。正常播放完成肯定是能拼接完整视频的，至于快进的，可能需要额外下载跳过部分才行。

**Comment by vieriwml** [comment]
@madongdong5550422 是这样的，现在我们的测试发现有些视频，在用resourceLoader来实现边下边播的时候，shouldWaitForLoadingOfRequestedResource这个函数对于播放片段的请求是乱序的，可能我当前的session还在下载0~65536这样的一个片段，但是shouldWaitForLoadingOfRequestedResource函数打出来的dataRequest请求的可能是一个109976~808789这样的一个片段了，和第一段完全无关，这种情况下如何才能做到继续播放呢，视频就只有顿住了呢。如果重新调整下载区间的话，那就无法进行快进的加载了。求思路指教~ 谢谢~

**Comment by madongdong5550422** [comment]
@vieriwml 第一个request是被avplayer取消掉了吗？avplayer要什么数据你就给它什么数据就行，取消上次下载，开始下载109976~808789。没明白“无法进行快进加载”是指的啥，快进的话，会产生一个新的request。

**Comment by vieriwml** [comment]
@madongdong5550422 我感觉很疑惑的就是这个地方，第一个requst并没有被取消, shouldWaitForLoadingOfRequestedResource直接就来请求一片靠后的数据，为了给它提供请求的数据，就只有把第一段的下载结束掉，然后开启新的下载，最后也无法下载完整的整个文件，播放也被异常的卡顿住。

**Comment by vieriwml** [comment]
@madongdong5550422 而且对于同一个在线短视频，avplayer也不是每次都跳序请求，有时候也是正常的能顺序的请求完成，很是疑惑~

**Comment by madongdong5550422** [comment]
@vieriwml 把链接给我，有时间我看一下

**Comment by ZetianChiang** [comment]
如果在缓冲的区域内拖动进度条是可以实现的，我在VideoTool.m中加入了 seekToTime:toleranceBefore:toleranceAfter: 的操作就可以了
