### ISSUE TITLE
在边缓冲边播放的时候暂停，多返回了一个JPVideoPlayerPlayingStatusPlaying的代理

### ISSUE THREAD

**Issue by ZetianChiang** [newyjp/JPVideoPlayer#106]
我的视频一边缓冲一边播放，在未缓冲完全的时候，此时pause视频，发现在KVO的loadedTimeRanges中，又执行了一次[self.delegate playVideoTool:self playingStatuDidChanged:JPVideoPlayerPlayingStatusPlaying];然后才开始回调JPVideoPlayerPlayingStatusBuffering，因为我的暂停按钮图标的切换需要在外部的xx_videoPlayerDelegate中通过status的改变去执行，多了一次这样错误的回调感觉我在外面要加一些BOOL判断，感觉有点伤😂

**Comment by newyjp** [comment]
Try version 3.0 please.
