### ISSUE TITLE
边下边播出现问题。

### ISSUE THREAD

**Issue by hujiudeyang** [newyjp/JPVideoPlayer#108]
具体是这样的。
JPVideoPlayer放在首页的viewcontroller中。可以边下边播。
但是UINavigationController push出来的viewcontroller中使用JPVideoPlayer，只能下载完成之后播放了，不能边下边播。

**Comment by newyjp** [comment]
Try version 3.0 please.

**Comment by newyjp** [comment]
Try version 3.0 please.

**Comment by newyjp** [comment]
Try version 3.0 please.
