### ISSUE TITLE
在DEMO中更改JPVideoPlayerDemoRowHei的数字后，视频的播放逻辑就乱了

### ISSUE THREAD

**Issue by YBYHunter** [newyjp/JPVideoPlayer#109]
在DEMO中更改JPVideoPlayerDemoRowHei的数字后，视频的播放逻辑就乱了。
#define JPVideoPlayerDemoRowHei ([UIScreen mainScreen].bounds.size.width*9.0/16.0)
我改成
#define JPVideoPlayerDemoRowHei ([UIScreen mainScreen].bounds.size.width*1/1)
出现的问题是 视频在屏幕中间，我上下滑时视频又从新播放了

**Comment by newyjp** [comment]
Try version 3.0 please.
