### ISSUE TITLE
Video not visible in landscape

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [newyjp/JPVideoPlayer#116]
Hi,

I'm using the v2.4.0 of this library in a Swift 4 project.

I fetch videos that are both portrait and landscape over the network. I don't have an issue playing portrait videos.

But when I call the `jp_gotoLandscape()`, the view goes off the screen. I can hear the video playing but can't see it. Below is my full code.

```swift
class ViewController: UIViewController {
    @IBOutlet weak var imageView: UIImageView!
    
    let portraitVideoUrl = URL(string: "http://dd0kufvmqwydf.cloudfront.net/dev/candidate/virendra-pratap-singh-5a8e72dba967a34112aae0f3/videos/5ab358319de56269b760db37/5ab358319de56269b760db37.mp4")
    let landscapeVideoUrl = URL(string: "http://dd0kufvmqwydf.cloudfront.net/dev/candidate/jacob-martin-5ab2485fa967a34112aae1ca/videos/5ab2490a9de56269b760db25/5ab2490a9de56269b760db25.mp4")
    
    
    @IBAction func didTapPortraitButton(_ sender: UIBarButtonItem) {
        imageView.jp_gotoPortrait()
        imageView.jp_playVideoHiddenStatusView(with: portraitVideoUrl)
    }
    
    @IBAction func didTapLandscapeButton(_ sender: UIBarButtonItem) {
        imageView.jp_gotoLandscape()
        imageView.jp_playVideoHiddenStatusView(with: landscapeVideoUrl)
    }
    
}
```

I've uploaded a demo project [here](https://www.dropbox.com/s/7isv1lqxzg5ibs8/JPVideoPlayerDemo.zip?dl=0).

**Comment by newyjp** [comment]
Try 3.0 please.

**Comment by Isuru-Nanayakkara** [comment]
Thanks. It does work. However there's a small caveat.

I have my imageview which acts as the player set up like this.

![screen shot 2018-04-12 at 8 30 21 am](https://user-images.githubusercontent.com/2551877/38655169-da8da4d6-3e30-11e8-831c-5a04c4bd704b.png)

On portrait, the video plays just fine.

![rsz_img_6702](https://user-images.githubusercontent.com/2551877/38655204-06869642-3e31-11e8-980c-3523798c3ff9.png)

On landscape, the rotation happens successfully. But as you can see, the video view overflows the imageview's bounds covering the navigationbar as well.

![rsz_img_6703](https://user-images.githubusercontent.com/2551877/38655253-448ec022-3e31-11e8-9fea-33299261a262.png)

How do I avoid this?

[Updated source](https://www.dropbox.com/s/v2kaehdkfm5pzvc/JPVideoPlayerDemo-updated.zip?dl=0)

**Comment by newyjp** [comment]
Try version 3.0 please.

**Comment by Isuru-Nanayakkara** [comment]
@newyjp Yes, this is happening after I updated to v3.0.

**Comment by newyjp** [comment]
try this [Demo.zip](https://github.com/newyjp/JPVideoPlayer/files/1907443/Demo.zip)

**Comment by newyjp** [comment]
stop play first before play a new video please.

**Comment by Isuru-Nanayakkara** [comment]
@newyjp Thanks. I ran it. The landscape works. But my problem is when the video is landscape, it covers the entire screen, including the navigation bar and all.

Is there a way to simply turn the video landscape inside the UIView only?

**Comment by newyjp** [comment]
You can see the landscape code in library, and copy it please.
