### ISSUE TITLE
最新版本系统会出现崩溃

### ISSUE THREAD

**Issue by wulingmianxianshengone** [newyjp/JPVideoPlayer#120]

**Comment by wulingmianxianshengone** [comment]
2018-04-16 11:25:33.474248+0800 JPVideoPlayerDemo[11498:326861] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 1]'
是因为没有加入UIKit框架的原因吗？

**Comment by newyjp** [comment]
直接跑的我的 demo，就崩溃了吗？

**Comment by newyjp** [comment]
什么机型？什么系统？

**Comment by wulingmianxianshengone** [comment]
是的

**Comment by wulingmianxianshengone** [comment]
iphone X  模拟器

**Comment by newyjp** [comment]
11.3 的 SDK？

**Comment by newyjp** [comment]
把那个崩溃信息全部贴上来

**Comment by wulingmianxianshengone** [comment]
11.2的  Deployment Target 8.0

**Comment by wulingmianxianshengone** [comment]
2018-04-16 11:27:26.916845+0800 JPVideoPlayerDemo[11530:332862] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010551212b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000104769f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105587245 +[NSException raise:format:] + 197
	3   QuartzCore                          0x00000001090c0d22 _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
	4   QuartzCore                          0x00000001090b15e8 -[CALayer setPosition:] + 43
	5   QuartzCore                          0x00000001090b1c16 -[CALayer setFrame:] + 544
	6   UIKit                               0x000000010267542e -[UIView(Geometry) setFrame:] + 368
	7   JPVideoPlayerDemo                   0x00000001018e7cdc -[JPVideoPlayerControlProgressView displayCacheProgressViewIfNeed] + 2716
	8   JPVideoPlayerDemo                   0x00000001018e716b -[JPVideoPlayerControlProgressView updateCacheProgressViewIfNeed] + 43
	9   JPVideoPlayerDemo                   0x00000001018e6207 -[JPVideoPlayerControlProgressView cacheRangeDidChange:] + 87
	10  JPVideoPlayerDemo                   0x00000001018e9289 -[JPVideoPlayerControlBar cacheRangeDidChange:] + 89
	11  JPVideoPlayerDemo                   0x00000001018eb0c9 -[JPVideoPlayerControlView cacheRangeDidChange:] + 89
	12  JPVideoPlayerDemo                   0x0000000101900ab9 -[UIView(WebVideoCache) videoPlayerManagerDownloadProgressDidChange:cacheType:fragmentRanges:expectedSize:error:] + 1785
	13  JPVideoPlayerDemo                   0x00000001018f6f89 __98-[JPVideoPlayerManager callDownloadDelegateMethodWithFragmentRanges:expectedSize:cacheType:error:]_block_invoke + 281
	14  JPVideoPlayerDemo                   0x00000001018d80bc JPDispatchSyncOnMainQueue + 156
	15  JPVideoPlayerDemo                   0x00000001018f6e00 -[JPVideoPlayerManager callDownloadDelegateMethodWithFragmentRanges:expectedSize:cacheType:error:] + 272
	16  JPVideoPlayerDemo                   0x00000001018f577a -[JPVideoPlayerManager downloader:didReceiveData:receivedSize:expectedSize:] + 810
	17  JPVideoPlayerDemo                   0x00000001018e0414 __62-[JPVideoPlayerDownloader URLSession:dataTask:didReceiveData:]_block_invoke_2 + 324
	18  JPVideoPlayerDemo                   0x00000001018d80bc JPDispatchSyncOnMainQueue + 156
	19  JPVideoPlayerDemo                   0x00000001018e029d __62-[JPVideoPlayerDownloader URLSession:dataTask:didReceiveData:]_block_invoke + 141
	20  JPVideoPlayerDemo                   0x00000001019095d6 __46-[JPVideoPlayerCacheFile addRange:completion:]_block_invoke + 726
	21  libdispatch.dylib                   0x000000010774a33d _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x00000001077573a0 _dispatch_sync_thread_bound_invoke + 386
	23  libdispatch.dylib                   0x000000010774a33d _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x00000001077555f9 _dispatch_main_queue_callback_4CF + 628
	25  CoreFoundation                      0x00000001054d4e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	26  CoreFoundation                      0x0000000105499462 __CFRunLoopRun + 2402
	27  CoreFoundation                      0x0000000105498889 CFRunLoopRunSpecific + 409
	28  GraphicsServices                    0x00000001089729c6 GSEventRunModal + 62
	29  UIKit                               0x00000001025c45d6 UIApplicationMain + 159
	30  JPVideoPlayerDemo                   0x00000001018e1a8f main + 111
	31  libdyld.dylib                       0x00000001077c6d81 start + 1
	32  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by newyjp** [comment]
你在这行代码打个断点：CGFloat cacheProgressViewOriginX = targetRange.location * self.trackProgressView.bounds.size.width / self.fileLength; 然后 po 一下 self.fileLength，把值贴上来。

**Comment by wulingmianxianshengone** [comment]
[DEBUG] [Thread: 01] ---------------输出数据--------1--------0
这个问题 不是每次又会出现的，不是必现的

**Comment by newyjp** [comment]
已经处理了。
