### ISSUE TITLE
播放前，有0.3秒黑屏时间。缓存的视频，cacheType总是JPVideoPlayerCacheTypeFragment

### ISSUE THREAD

**Issue by JFZheng** [newyjp/JPVideoPlayer#121]
1：每次开始播放视频，开始播放前，都要黑大概0.3秒，才能显示图像，经查询，默认播放视图是透明的，可以自己设置黑色，但是我设置的是透明的，依然有黑屏0.3秒左右。2：播放过的视频，cacheType总是JPVideoPlayerCacheTypeFragment。

**Comment by newyjp** [comment]
老哥你倒是留个视频链接啊，你原封不动拷过来，这个 bug 我排不了。
