### ISSUE TITLE
关于3.0不灭屏的问题和混合播放的问题

### ISSUE THREAD

**Issue by wenhao-fly** [newyjp/JPVideoPlayer#122]
1.播放的时候手机不灭屏，一直亮着播放  有没有设置的方法 有这个需求，我设置[[UIApplication sharedApplication] setIdleTimerDisabled:NO]无效。 2.我需要视频播放的时候 网易云音乐也可以播放。但框架里用的AVAudioSessionCategoryPlayback模式。 我改成AVAudioSessionCategoryAmbient模式视频会没有声音了, 这是怎么回事,望指教,谢谢

**Comment by newyjp** [comment]
试一下 3.0.5, 提供了播放前自定义 audioSessionCategory 的入口。

**Comment by wenhao-fly** [comment]
恩第二个问题解决了 第一个不灭屏的问题怎么解决
