### ISSUE TITLE
当videoView不在可视范围内的时候

### ISSUE THREAD

**Issue by suweiz19890921** [newyjp/JPVideoPlayer#126]
当videoView不在可视范围内的时候，如果当前visibleCells中有两个cell， 一个有视频，一个没有视频，没有视频的cell在可视范围内，有视频的cell不在可视范围内，没在可视范围内的cell还在继续播放视频。targetCell 赋值的时候还是要做下判断！
![snip20180418_18](https://user-images.githubusercontent.com/17306517/38929354-93786f1e-433e-11e8-82fc-6fbc63bb8a47.png)

**Comment by newyjp** [comment]
试一下 3.0.4
