### ISSUE TITLE
悬停播放的时候，滑动会从头播放

### ISSUE THREAD

**Issue by chuzhaozhi** [newyjp/JPVideoPlayer#127]
大佬,首先收下我膜拜的膝盖，其次我发现悬停播放的时候，我点击了暂停，然后滑动UITableView的时候，小窗口是从头开始播放的，这个时候回到顶部的时候，视频也是从头开始播放的，暂停按钮也对应显示的不对了

**Comment by newyjp** [comment]
3.0.5 版本修复了这个问题, 试试看吧。

**Comment by chuzhaozhi** [comment]
我下载了你这个工程，跑了一下是在cell上的暂停了，滑动之后小窗口是从头开始播放的，暂停播放按钮显示的也不对

**Comment by newyjp** [comment]
是 3.0.5 版本吗？

**Comment by chuzhaozhi** [comment]
是的，刚在github上直接下载的
