### ISSUE TITLE
有些视频在开始播放的时候会有短暂的黑屏现象

### ISSUE THREAD

**Issue by Jack-Rain** [newyjp/JPVideoPlayer#132]
有些视频在开始播放的时候会有短暂的黑屏现象

**Comment by newyjp** [comment]
播放器通知已经开始播放的时候，其实播放器并没有开始显示画面，可以通过代理方法 `-shouldShowBlackBackgroundWhenPlaybackStart` 来控制是否播放的时候是否显示黑色背景。
