### ISSUE TITLE
关闭自动重播，播放结束后回调中得不到播放结束的回调，得到是缓冲状态。一直在缓冲

### ISSUE THREAD

**Issue by BotBrain** [newyjp/JPVideoPlayer#133]
![simulator screen shot - iphone 8 - 2018-04-23 at 17 59 42](https://user-images.githubusercontent.com/30071237/39120731-e0d4eaa8-4721-11e8-95bf-840ce21bcd6b.png)

**Comment by newyjp** [comment]
新版已经修复，谢谢支持。

**Comment by 624990742** [comment]
你好请问，结束的回调是哪一个方法呢？

**Comment by 624990742** [comment]
为什么播放器一直播放停止不了呢？
