### ISSUE TITLE
ios10 缓冲一会之后会发生 error

### ISSUE THREAD

**Issue by jackey-jiang** [newyjp/JPVideoPlayer#139]
![image](https://user-images.githubusercontent.com/10288803/39225709-6b25ccea-4880-11e8-9e9d-54f74f633112.png)

**Comment by newyjp** [comment]
测试过 iOS 10.3.1，没有发生你碰到的问题，最好描述一下你是在什么情况下碰到问题的，方便我重现。

**Comment by gjterry** [comment]
iOS 10.3.3  初次打开视频一直处于缓冲，无法播放，之后就会抛出@jacky-jiang截屏的内容。当视频下载完成后再次打开可以正常播放
