### ISSUE TITLE
只支持mp4格式

### ISSUE THREAD

**Issue by ox-man** [newyjp/JPVideoPlayer#147]
你好，在使用并看了你的代码之后，发现了两个可以改进的问题：
<1>目前仅支持mp4的视频格式；
<2>使用AVPlayer可以在线播放音频。由于是以mp4格式存储在沙盒中，所以在播放沙盒缓存的数据的时候，会出现问题；
所以，我给出下面建议：
在`JPVideoPlayerCachePath`文件中，
`static NSString * const kJPVideoPlayerCacheVideoFileExtension = @".mp4";`
在`+ (NSString *)videoCachePathForKey:(NSString *)key`方法中：
`filePath = [filePath stringByAppendingString:kJPVideoPlayerCacheVideoFileExtension];`
代码建议替换成：
`NSString *fileType = [NSString stringWithFormat:@".%@",[key pathExtension]];`
`filePath = [filePath stringByAppendingString:fileType];`
这样根据视频链接来判断文件类型，不仅可以播放各类型的视频，也可以播放音频。
整个工程中共有三处使用到mp4格式的拼接，都在`JPVideoPlayerCachePath`文件中。望采纳。谢谢。

**Comment by newyjp** [comment]
方便提交一个 PR 吗？

**Comment by newyjp** [comment]
3.1.0 会解决这个问题，这两天更新。
