### ISSUE TITLE
视频下载完成后只有声音没有画面

### ISSUE THREAD

**Issue by tangtiancheng** [newyjp/JPVideoPlayer#151]
作者你好,我这边有时会出现播放一个网络mp4视频,边下边播完成之后,那个本地文件只有声音没有画面的BUG,然后我把应用卸载了之后,再运行还是播放这个网络链接,就好了,本地的视频有声音有画面,也就是说这个视频链接是没问题的才对
![2018-05-15 11 01 40](https://user-images.githubusercontent.com/26619358/40034439-8a400c30-582f-11e8-808d-c385a02eb300.png)

**Comment by newyjp** [comment]
链接给下。
