### ISSUE TITLE
通过CocoaPods集成缺失了JPVideoPlayer.bundle

### ISSUE THREAD

**Issue by xiaopin** [newyjp/JPVideoPlayer#154]
如题，通过CocoaPods的方式集成了该库，但是缺失了JPVideoPlayer.bundle，导致controlView传nil的时候，默认的控制视图中播放/暂停按钮以及全屏切换按钮的图标不显示

pod 'JPVideoPlayer', '~> 3.0.9'

**Comment by newyjp** [comment]
先移除框架，重新安装一遍
