### ISSUE TITLE
iOS 10.3.3没办法边下载边播

### ISSUE THREAD

**Issue by gjterry** [newyjp/JPVideoPlayer#155]

**Comment by gjterry** [comment]
暂时取消改handleVideoURL 为视频源地址 取消下载功能，有无更好的解决方案。

**Comment by tangtiancheng** [comment]
确实低于11没法边下边播,是下完才播放,还好你发了这个问题,要不我就直接发包了,好险

**Comment by yanashenyang** [comment]
10.3.3无法播放怎么解决

**Comment by sharon2sun** [comment]
http://image.g2u.livearts.cn/videoTmp_20180514143426_DUID_59b5f8b3a3b33isgsXlZT0g_13126.mp4 , 这个在11以下要下载完才播

**Comment by tangtiancheng** [comment]
你好,我是直接跑的您写的Demo,在10.2和10.3真机上都试了,都是必须下载完成之后才会播放,但是在模拟器上是正常边下边播的,  在真机上11的系统是可以正常播放的
