### ISSUE TITLE
后台切换回来会自动播放

### ISSUE THREAD

**Issue by aemoe** [newyjp/JPVideoPlayer#156]
感谢作者组件
但是请问下
后台切换回来如何保持原来状态
比如 播放或者暂停
回来状态不变

我尝试了接口方法 
shouldResumePlaybackWhenApplicationDidBecomeActiveFromBackground
给 return false 并没有用

**Comment by newyjp** [comment]
fixed on 3.1.0.

**Comment by aemoe** [comment]
Thx ~

**Comment by thinking001** [comment]
请问你的ok了吗？我的3.1.1版本仍然有这个问题，使用swift开发，具体怎么解决的？
