### ISSUE TITLE
iOS11上面可以边下边播,iOS11以下就不可以了

### ISSUE THREAD

**Issue by tangtiancheng** [newyjp/JPVideoPlayer#163]
iOS11上面可以边下边播,iOS11以下就不可以了,这个问题能修复一下吗

**Comment by newyjp** [comment]
留个视频链接。

**Comment by tangtiancheng** [comment]
你好,我是直接跑的您写的Demo,在10.2和10.3真机上都试了,都是必须下载完成之后才会播放,但是在模拟器上是正常边下边播的,  在真机上11的系统是可以正常播放的
