### ISSUE TITLE
视频在播放时显示左右边距

### ISSUE THREAD

**Issue by croozeus** [newyjp/JPVideoPlayer#177]
在TableViewcell中播放视频会在左侧和右侧显示一些边距。

我正在使用已有图像的ImageView。

我明天可以发布截图。

抱歉中文不好，我使用谷歌翻译。

English version:

Playing the video in TableViewcell shows some margin on left and right sides. 
I am playing in ImageView which already has an image.

I can post a screenshot tomorrow.

Sorry for bad chinese, I used Google Translate.

**Comment by croozeus** [comment]
![screen shot 2018-07-04 at 10 36 18 am](https://user-images.githubusercontent.com/3419509/42257866-613da9f0-7f76-11e8-8201-10421825cc75.png)

**Comment by newyjp** [comment]
/**
     * Stretch to fill layer bounds.
     */
    JPVideoPlayerLayerVideoGravityResize = 1 << 5,

    /**
     * Preserve aspect ratio; fit within layer bounds.
     * Default value.
     */
    JPVideoPlayerLayerVideoGravityResizeAspect = 1 << 6,

    /**
     * Preserve aspect ratio; fill layer bounds.
     */
    JPVideoPlayerLayerVideoGravityResizeAspectFill = 1 << 7,

Do you can see this ?

**Comment by newyjp** [comment]
```objective-c
/**
* Stretch to fill layer bounds.
*/
JPVideoPlayerLayerVideoGravityResize = 1 << 5,

/**
 * Preserve aspect ratio; fit within layer bounds.
 * Default value.
 */
JPVideoPlayerLayerVideoGravityResizeAspect = 1 << 6,

/**
 * Preserve aspect ratio; fill layer bounds.
 */
JPVideoPlayerLayerVideoGravityResizeAspectFill = 1 << 7,
```

Do you can see this ?
