### ISSUE TITLE
新特性：UICollectionView 的支持

### ISSUE THREAD

**Issue by frankxzx** [newyjp/JPVideoPlayer#180]
类似微博的 cell 自动播放暂停， 使用 IGListKit 需要支持 UICollectionView

**Comment by newyjp** [comment]
你能基于我之前写的 tableView 的支持一下 `UICollectionView` 帮我 pull request ?

**Comment by heiguoliangle** [comment]
> 类似微博的 cell 自动播放暂停， 使用 IGListKit 需要支持 UICollectionView

我也在用IG,大佬能把代码发下么
