### ISSUE TITLE
 proposal for updating and improving the logo for

### ISSUE THREAD

**Issue by orlant** [newyjp/JPVideoPlayer#181]
hello for me it is a pleasure to be here I am a graphic designer and I like to make collaborations in projects like this, if you allow me I can design a new image for the use of this application?

**Comment by newyjp** [comment]
You can do it, but it’s  a free project as you know, so I hava no money pay for you and, thank you anyway.

**Comment by orlant** [comment]
For me it would be a pleasure to design for you, it would be a pride that my proposal if it meets the expectations can be added to your repository. Do not worry about the payment. My contribution will be free for you. come back so soon to show you the results you think?

**Comment by newyjp** [comment]
![](https://user-images.githubusercontent.com/14839923/42406217-822eafcc-81d5-11e8-8ee6-938932d020cf.png)

**Comment by newyjp** [comment]
This logo was designed by myself, it's maybe uglily in professional designer eyes, but it's looks not bad in a coder eyes 😝.

**Comment by orlant** [comment]
good only some details when you joined the green apple and fuchsia gradient layers, you should line them up carefully. "Quiet is a good start as designer friend felicidades", taking up the theme and taking into account this main idea, you will see what I will bring for you and I am at this moment working on this.

**Comment by orlant** [comment]
hello like the pass? For me it is a pleasure to be able to return with good news ... I have already done something for you I hope you like it.

I created a logo using the old logo as a reference, which you mentioned but now I only update it using the initials of JP, which if I'm not mistaken is your name, the base icon is the Play symbol of a player. enjoy it.


![presentacion](https://user-images.githubusercontent.com/40074778/42415357-77e14a4a-8219-11e8-99e6-83c5ab78f1ca.png)

**Comment by orlant** [comment]
I want to know what you think, and what kind of letters you want to use, you have 3 different logo options, and below you put a classification of the logomark in case you want to make some combination with the given colors

**Comment by newyjp** [comment]
Thank you at first.

I think video represent the colorful world and, I present my idea by the three primary colors(red, green, blue). I always hope the logo can take me a colorful feeling.

`JP` is my first name, but I don't wanna you use it on the play symbol, because it looks not fancy.  

I wanna user like the color we used on logo, and they remember it, so we don't need to write a `JP` on logo, they know it are `JPVideoPlayer` when see the color. 

Sorry I don't like the color you provided, I like the color in my origin logo yet. the black mask make the logo looks dirty, I don't like it 😢.

**Comment by orlant** [comment]
Many thanks for your comments, I think that if I had this information before it would have been better and it was just an idea, if you want I can make another version. without compromising it only so that it sees.

**Comment by newyjp** [comment]
Thank you for your reply, you can try it if you wanna. I look forward to see the new version.
