### ISSUE TITLE
播放本地中文名文件的bug

### ISSUE THREAD

**Issue by dagundejuzi** [newyjp/JPVideoPlayer#182]
本地文件如果是中文名，会播不了。在JPVideoPlayerManager.m  第617行加句：path = path.stringByRemovingPercentEncoding; 就可以了。
![image](https://user-images.githubusercontent.com/16382880/42407514-796b3e94-81f0-11e8-8c2a-9e36b1f5fad4.png)

**Comment by newyjp** [comment]
好，下个版本做，蟹蟹 :)
