### ISSUE TITLE
想问下，视频续播(接着播放)，只能在同一个视频播放的情况下吗？

### ISSUE THREAD

**Issue by carlchou00** [newyjp/JPVideoPlayer#193]
譬如说，我先播放A视频，再把A视频停掉，再播B视频，现在再重新播放A视频，用resume的播放方法是从头开始播放的，这个有办法吗？我看原码里，resume播放有判断是不是同一个url地址，如果不是则不能续播

**Comment by newyjp** [comment]
你全部使用 resume 来播放就可以了，你就不用担心这些了。

**Comment by tangyumeng** [comment]
> 譬如说，我先播放A视频，再把A视频停掉，再播B视频，现在再重新播放A视频，用resume的播放方法是从头开始播放的，这个有办法吗？我看原码里，resume播放有判断是不是同一个url地址，如果不是则不能续播

可以实现续播么？ 试了下，resume 好像也不行？

**Comment by carlchou00** [comment]
不行的，如果一个视频停掉了，他本地保存的记录(A视频对应的Url地址播放到多少秒)就会被清理掉，所以只能重头开始播放，你改源码的话应该可以实现，具体我没有试过

**Comment by tangyumeng** [comment]
> 不行的，如果一个视频停掉了，他本地保存的记录(A视频对应的Url地址播放到多少秒)就会被清理掉，所以只能重头开始播放，你改源码的话应该可以实现，具体我没有试过
感谢回复。后来换用 SJVideoPlayer 实现续播
