### ISSUE TITLE
How to add JPVideoPlayer to Project without CocoaPods

### ISSUE THREAD

**Issue by maulikpat** [newyjp/JPVideoPlayer#195]
Hello,

I have downloaded/cloned the project. I copied the JPVideoPlayer folder to my project.
When I tried to build/Run it gives me many errors like : 
`A parameter list without types is only allowed in a function definition` in `JPVideoPlayer.m` file.

Is there any extra settings to configure this library ?

**Comment by CranberryYam** [comment]
I only added the JPVideoPlayer folder to my project and it works

**Comment by newyjp** [comment]
why do not you use Cocoapods ?
