### ISSUE TITLE
seekToTime crash

### ISSUE THREAD

**Issue by suweiz19890921** [newyjp/JPVideoPlayer#198]
![snip20180813_13](https://user-images.githubusercontent.com/17306517/44020261-f61056e2-9f13-11e8-9496-fdab77fe89ef.png)
![snip20180813_14](https://user-images.githubusercontent.com/17306517/44020262-f64b0daa-9f13-11e8-92aa-104180b8e938.png)

**Comment by luoliying** [comment]
crash too....

**Comment by carlchou00** [comment]
same here

-[JPVideoPlayer seekToTime:] (JPVideoPlayer.m:391)
-[JPVideoPlayerManager seekToTime:] (JPVideoPlayerManager.m:290)
-[UIView(WebVideoCache) jp_seekToTime:] (UIView+WebVideoCache.m:425)
-[NFVideoPlayerControlProgressView userDidFinishDrag] (NFVideoPlayerControlViews.m:314)
-[NFVideoPlayerControlProgressView dragSliderDidEnd:] (NFVideoPlayerControlViews.m:305)

**Comment by newyjp** [comment]
I will fix it on next version, thanks.
