### ISSUE TITLE
请问JPVideoPlayerManager.m中 ，这个断言的作用是防止什么？我总是崩溃在这里

### ISSUE THREAD

**Issue by invokeHao** [newyjp/JPVideoPlayer#205]
![image](https://user-images.githubusercontent.com/26423009/46204521-18763480-c350-11e8-980e-ae4421e98239.png)

**Comment by CranberryYam** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/11156068/46960992-c6caeb00-d06d-11e8-94ee-83ea99c28e8e.png">
我是崩溃在这个断言, 作者为什么要加这么多断言?

**Comment by mjf1986** [comment]
pod install 下来，支持三个url,超过就会崩溃，JPVideoPlayerManager.m总是崩溃。

**Comment by invokeHao** [comment]
我把断言那句话，用if容错掉，然后就没有崩溃了

**Comment by CranberryYam** [comment]
Me too

**Comment by CranberryYam** [comment]
> 我把断言那句话，用if容错掉，然后就没有崩溃了

你知道, 作者为什么要加这么多assertion吗?

**Comment by newyjp** [comment]
断言去掉了，为了排除 bug 加的断言.
