### ISSUE TITLE
[JPVideoPlayerCacheFile cachedRangeContainsPosition:]第167行崩溃了

### ISSUE THREAD

**Issue by carlchou00** [newyjp/JPVideoPlayer#206]
![screen shot 2018-10-02 at 11 20 10](https://user-images.githubusercontent.com/13175918/46327709-af373f80-c635-11e8-9b99-766280e6ca4c.png)

**Comment by newyjp** [comment]
看不出问题出在哪。

**Comment by sunjianan** [comment]
这个问题还没有解决怎么就关掉了呢？   同崩溃在197行
