### ISSUE TITLE
UITableView居中自动播放存在一些bug

### ISSUE THREAD

**Issue by FelixYin66** [newyjp/JPVideoPlayer#211]
![0d0a809d-e92d-4159-87b3-86c1fa580d5c](https://user-images.githubusercontent.com/12432386/50088369-cbfb1080-023d-11e9-81aa-d20d61ca4327.png)

CGFloat gap = MAXFLOAT;
...中间代码省略
CGPoint coordinateCenterPoint = [strategyView.superview convertPoint:strategyView.center toView:nil];
            CGFloat delta = fabs(coordinateCenterPoint.y - referenceRect.size.height * 0.5 - referenceRect.origin.y);
            if (delta < gap) {
                gap = delta;
                targetCell = cell;
            }
delta值小于gap值属于恒成立的，也就是说离中心y值有很大一段距离也会自动播放。应该将JPVideoPlayerSupportUtils中617行代码修改成

CGPoint coordinateCenterPoint = [strategyView.superview convertPoint:strategyView.center toView:nil];
            CGFloat delta = fabs(coordinateCenterPoint.y - referenceRect.size.height * 0.5 - referenceRect.origin.y);
//50是我设定的值，可按照情况修改
            if (delta < 50) {
                gap = delta;
                targetCell = cell;
            }

**Comment by newyjp** [comment]
fixed, thank u.
