### ISSUE TITLE
JPVideoPlayerView自定义控制视图，无法处理事件

### ISSUE THREAD

**Issue by ywdonga** [newyjp/JPVideoPlayer#212]
如图所示，当自定义控制视图时，发现JPVideoPlayerView的subView盖在控制视图上面，导致无法处理事件。
![image](https://user-images.githubusercontent.com/16291063/50396776-f9e4d580-07a6-11e9-886d-843e4a9576b6.png)

**Comment by xiaoguiguitu** [comment]
我也遇到了这个问题，我就把里面的框架给修改了，要不然怎么都处理不了

**Comment by newyjp** [comment]
当用户点击播放按钮，才开始创建播放器视图，添加到指定的 view A 上，这本来就没有问题。

此时，可以在指定的 A 的 superview 上创建一个和 A 平级的 view B，把你的控制附件添加在 B 上，就不会挡住你的控件了。

iOS 入门知识。
