### ISSUE TITLE
本地视频播放问题

### ISSUE THREAD

**Issue by TML007** [newyjp/JPVideoPlayer#222]
这种带中文本地视频：/var/mobile/Containers/Data/Application/2680AFB2-4008-496C-969C-AA4D3A465C6F/Documents/Screenshot/2019年01月24日 19:23:52.mp4    用这个方法- (void)jp_playVideoWithURL:(NSURL *)url
         bufferingIndicator:(UIView <JPVideoPlayerBufferingProtocol> *_Nullable)bufferingIndicator
                controlView:(UIView <JPVideoPlayerProtocol> *_Nullable)controlView
               progressView:(UIView <JPVideoPlayerProtocol> *_Nullable)progressView
              configuration:(JPPlayVideoConfiguration _Nullable)configuration;播放不了

**Comment by newyjp** [comment]
<img width="410" alt="screen shot 2019-03-03 at 11 33 19 pm" src="https://user-images.githubusercontent.com/14839923/53697509-c3fa4800-3e0c-11e9-96dc-61e1376e1eec.png">

这个文件名是非法的。
