### ISSUE TITLE
是否能提供主动刷新播放tableview上的cell的视频的方式

### ISSUE THREAD

**Issue by shafujiu** [newyjp/JPVideoPlayer#226]
[情况大概是这样，当我们滚动正常播放视频是可以的没有问题，但是当我们在做当前单元格刷新之后，我们的视屏播放就没有被渲染出来

**Comment by shafujiu** [comment]
[参考视频](https://github.com/shafujiu/resource/ScreenRecording_02-26-2019 17-23-35.MP4) 视频只要一个下载地址 抱歉

**Comment by shafujiu** [comment]
我用你的demo也做过测试，如果单独刷新某个cell 视频播放器就不见了，看有没有主动调起的方式

**Comment by newyjp** [comment]
刷新完成，你要调用 `jp_resumePlayWithURL`，刷新完成 cell 都变了，肯定要处理一下。

**Comment by shafujiu** [comment]
嗯 先让停止 然后再次调起可以，只是体验稍微差一些。
