### ISSUE TITLE
3.2.0 bate 版本 播放器的进度条没有显示

### ISSUE THREAD

**Issue by shafujiu** [newyjp/JPVideoPlayer#228]

**Comment by shafujiu** [comment]
从列表到详情播放没有问题，从详情到详情的下级页面操作之后返回，重新通过jp_resumePlayWithURL 调起播放的时候，你会发现播放器无论是最底部还是UISlider 都没有，点击之后恢复正常。

**Comment by newyjp** [comment]
fixed, thank u.
