### ISSUE TITLE
Category UIView (WebVideoCacheOperation) 与SDWebImage的Category重名导致lldb po报错

### ISSUE THREAD

**Issue by FFFang** [newyjp/JPVideoPlayer#232]
(lldb) po self
error: instance method 'supportedInterfaceOrientations' has incompatible result types in different translation units ('UIInterfaceOrientationMask' vs. 'NSUInteger' (aka 'unsigned long'))
instance method 'supportedInterfaceOrientations' also declared here

**Comment by newyjp** [comment]
项目里没有用到这个 symbol.
