### ISSUE TITLE
播放视频时滑动，cell超出界面停止播放时有一个卡顿的现象

### ISSUE THREAD

**Issue by ohjam** [newyjp/JPVideoPlayer#37]
播放视频时滑动，cell超出界面停止播放时有一个卡顿的现象，demo中也有这个现象存在

**Comment by newyjp** [comment]
什么设备?

**Comment by ohjam** [comment]
iphone6s 还没解决怎么就close了呢

**Comment by newyjp** [comment]
没有碰到你所描述的卡顿, 我在 iPhone 5 上测试都没有卡顿, 所以没有办法重现你的问题, 请你排查自己的代码逻辑. 谢谢支持.
