### ISSUE TITLE
播放七牛云视频总失败

### ISSUE THREAD

**Issue by hydyy** [newyjp/JPVideoPlayer#41]
https:/videossl.edujia.com/team/video/6oley/seq/A7FE2CB3-BF1F-47CA-8843-BB56C63D6A54.mp4

这个链接，总是失败，但是在浏览器打开是没有问题的

**Comment by newyjp** [comment]
https 协议不应该是这样写吗: https:// ? 你看看你自己的协议是怎么写的?
