### ISSUE TITLE
部分视频不支持边下边播

### ISSUE THREAD

**Issue by MimiOuO** [newyjp/JPVideoPlayer#43]
潘神，部分视频不支持边下边播，不知是不是播放器解码问题，附上视频地址
  @"http://www.xiaomatv.cn/%E6%B8%A9%E5%B7%9E%E6%99%AE%E6%8B%89%E5%A4%9A%E7%BA%B5%E9%98%9F%E6%8E%A2%E7%A7%98%E7%BD%97%E5%B8%83%E6%B3%8A%EF%BC%8C%E7%A9%BF%E9%98%BF%E5%B0%94%E9%87%91%E5%B1%B1%E8%87%AA%E9%A9%BE%E8%A1%8C_%E6%A0%87%E6%B8%85.mp4",
@"http://www.xiaomatv.cn/Mercedes%20G%20class.mp4",
@"http://www.xiaomatv.cn/Long%20Tom%20Hill%20climb%20after%20rain%20-%20Landcruiser%2080%20series.mp4",
@"http://www.xiaomatv.cn/land%20cruiser%2076%20off%20road.mp4",                    @"http://www.xiaomatv.cn/F%3A%2Fyoutube%E7%B4%A0%E6%9D%90%2FLC76%2FCape%20York%202013%20-%204x4%20trip%20via%20the%20Old%20Telegraph%20Track.mp4",

**Comment by newyjp** [comment]
有些视频的 metedata 在视频尾部, 导致视频不能边下载边播放, 谢谢支瓷.
