### ISSUE TITLE
iOS11 系统出现crash

### ISSUE THREAD

**Issue by angBiu** [newyjp/JPVideoPlayer#45]
-[OS_dispatch_data subdataWithRange:]: range {1736704, 7047} exceeds data length 946764

**Comment by wangzuowen0825** [comment]
这个问题你解决了么,我也遇到了

**Comment by zackschen** [comment]
看来都是iOS 11下遇到的

**Comment by zackschen** [comment]
NSRange dataRange = NSMakeRange((NSUInteger)startOffset- self.manager.offset, (NSUInteger)numberOfBytesToRespondWith);
    if (NSMaxRange(dataRange) > fileData.length) {
        return NO;
    }
判断一下需要response的长度，如果比本地下载的长，就不响应这个请求。
我目前改了不crash了,可以试下。

**Comment by newyjp** [comment]
试一下 3.0 版本，这个 issue 我关掉了。
