### ISSUE TITLE
在 cell 中设置进度条颜色后，进度条位置会偏移

### ISSUE THREAD

**Issue by clayzhu** [newyjp/JPVideoPlayer#46]
使用[自定义进度颜色](https://github.com/newyjp/JPVideoPlayer#自定义进度指示颜色下载和播放进度)时，如果是在 cell 中播放。设置后，进度条位置会偏移。

**设置代码：**
![image](https://user-images.githubusercontent.com/8502741/27125299-73490ea2-5126-11e7-9473-d9d4de2a32d6.png)

**进度条位置偏移：**
![image](https://user-images.githubusercontent.com/8502741/27125746-dcb2ec86-5127-11e7-8bb9-b303e09fa7d2.png)

**Comment by clayzhu** [comment]
如果 view 是使用 AutoLayout 创建的话，会有这个问题。使用代码设置 frame 是正常的。

点击横屏也是这样的问题。

**Comment by newyjp** [comment]
由于 frame 和 Autolayout  的冲突关系, 所以建议你需要横屏的那个视频 view 用 frame 的方式进行布局. 谢谢支持.
