### ISSUE TITLE
播放卡死

### ISSUE THREAD

**Issue by Leon-OS** [newyjp/JPVideoPlayer#48]
@"http://v.autoimg.cn/v/club/2017/06/17/4dd7548b9f334203bc6c6d3c519bebd4_w272_h272.mp4"
这个视频，在限制网速100k，播放不出来

**Comment by newyjp** [comment]
没下载到数据肯定没法播啊! 谢谢支瓷.

**Comment by Leon-OS** [comment]
但是其他的视频源就可以

**Comment by newyjp** [comment]
你都知道是视频源导致的, 那你就解决视频源的问题就可以了.
