### ISSUE TITLE
整个视频下载完才播放

### ISSUE THREAD

**Issue by onechao** [newyjp/JPVideoPlayer#53]
有问题的视频：http://zthome.ztjystore.cn/ltvZFllpBePw8P-PESfuYRqChV2G
这个视频大概有500M左右，无法做到边下边播，请问视频在什么情况下才导致这种情况出现，谢谢。

**Comment by newyjp** [comment]
我也一直致力于找解决办法, 从我现在看过的资料来看, 没法在 AVPlayer 实现正真的边下载边播放, 但是不排除 FFmpeg 可以, 接下来我会去尝试使用 FFmpeg, 如果 OK 了, 就写 3.0 版本.

**Comment by newyjp** [comment]
Try version 3.0 please.
