### ISSUE TITLE
Can not play video from URl with local path.

### ISSUE THREAD

**Issue by KanybekMomukeyev** [newyjp/JPVideoPlayer#54]
@newyjp hi, thanks for sharing code!
Is it possible to play video from local path, like this

```
file:///Users/user/Library/Developer/CoreSimulator/Devices/5D5434B8-71C9-41C3-9038-1CFB387C8F43/data/Containers/Data/Application/C4F6B123-4372-4B71-A87B-EB59ABA6FA77/Library/Caches/4487/a417/e7fd/0331/34b3/edf3/1a85/9437/4487a417e7fd033134b3edf31a859437cfd6744d74374f474be69affa1a19432
```
like this one

```
let documentsURL = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask)[0]
let fileURL = documentsURL.appendingPathComponent("localPath")
            
if FileManager.default.fileExists(atPath: fileURL.path) {
               print("FileManager.default.fileExists")
               cellImageView.jp_playVideo(with: fileURL)

}

```

I have tried to play video, but still no sucess

**Comment by newyjp** [comment]
hi, JPVideoPlayer support local path video, but your path "file:///Users/user/Library/Developer/CoreSimulator/Devices/5D5434B8-71C9-41C3-9038-1CFB387C8F43/data/Containers/Data/Application/C4F6B123-4372-4B71-A87B-EB59ABA6FA77/Library/Caches/4487/a417/e7fd/0331/34b3/edf3/1a85/9437/4487a417e7fd033134b3edf31a859437cfd6744d74374f474be69affa1a19432" looks not like a video, please check out it.

**Comment by KanybekMomukeyev** [comment]
@newyjp how did you understand, that it is not video, it should be like? :
```
"file:///blabla/some.mp4"
"file:///blabla/some.avi"
"file:///blabla/some.mov"
```

**Comment by newyjp** [comment]
I don't care the type of your file, but the `AVPlayer` maybe care. please read that code:
NSURL *videoPathURL = [NSURL fileURLWithPath:fullVideoCachePath];
AVURLAsset *videoURLAsset = [AVURLAsset URLAssetWithURL:videoPathURL options:nil];
AVPlayerItem *playerItem = [AVPlayerItem playerItemWithAsset:videoURLAsset];
item.player = [AVPlayer playerWithPlayerItem:playerItem];

**Comment by KanybekMomukeyev** [comment]
@newyjp yes, you are correct, this is my mistake, video format is not correct
