### ISSUE TITLE
视频播放未完成会卡住,再次播放就可以（视频已下载完成）

### ISSUE THREAD

**Issue by xiaopangxie** [newyjp/JPVideoPlayer#57]
http://video.quliao.com/20170710/D6452658F2074AB6B20C9F3218F6051C.mp4

**Comment by weidongliu** [comment]
@xiaopangxie 你好，我也有偶尔遇到这个问题，请问有解决的方法吗？

**Comment by Jack-Rain** [comment]
@weidongliu 我也是

**Comment by weidongliu** [comment]
@Jack-Rain 是个难题阿，找遍网上都没找相关的资料

**Comment by Jack-Rain** [comment]
https://github.com/vitoziv/VIMediaCache/issues/21 @weidongliu 可以一试

**Comment by weidongliu** [comment]
@Jack-Rain 谢谢哈，我看看

**Comment by newyjp** [comment]
Try version 3.0 please.
