### ISSUE TITLE
从2.2.3升级到2.2.4自动播放崩溃

### ISSUE THREAD

**Issue by xiayp** [newyjp/JPVideoPlayer#60]
- (id<JPVideoPlayerDelegate>)jp_videoPlayerDelegate{
    id (^__weak_block)() = objc_getAssociatedObject(self, _cmd);
    return __weak_block();   //这个位置 崩溃Thread 1:EXC_BAD_ACCESS(code=1,address=0x10)
}

在2.2.3的版本，ios9所有地方的输入框收起键盘崩溃，在2.2.4版本，收起键盘不会崩溃了，但是自动播放直接崩溃

**Comment by newyjp** [comment]
没有出现你说的奔溃, 排查一下你自己的代码吧. 谢谢支持.
