### ISSUE TITLE
同时播放音乐

### ISSUE THREAD

**Issue by xiayp** [newyjp/JPVideoPlayer#64]
可以在播放视频的同时播放音乐吗？使用静音播放视频，然后继续听手机音乐。

**Comment by xiayp** [comment]
能回答一下么？静音播放的时候，要求继续听音乐，然后有声播放视频的时候，视频结束后继续播放音乐，跟微博一样的。

**Comment by Onion520** [comment]
这个你可以搜索一下AVAudioSession  有你想要的答案

**Comment by newyjp** [comment]
Try version 3.0 please.
