### ISSUE TITLE
如何监听播放完成了

### ISSUE THREAD

**Issue by GreatLiyi** [newyjp/JPVideoPlayer#66]
如题

**Comment by betterton** [comment]
我在JPVideoPlayerTool的playerItemDidPlayToEnd方法中添加了一个finsh的enum…… 希望作者可以添加这个功能以及seek功能 因为要实现需求侵入式修改了很多……

**Comment by newyjp** [comment]
- (BOOL)shouldAutoReplayAfterPlayCompleteForURL:(nonnull NSURL *)videoURL; 这个代理方法不就是你要的吗?
