### ISSUE TITLE
获取缓存大小的时候，发现获取的不对

### ISSUE THREAD

**Issue by wangduan7639** [newyjp/JPVideoPlayer#67]
NSDirectoryEnumerator *fileEnumerator_full = [_fileManager enumeratorAtPath:fullFilePath];
            for (NSString *fileName in fileEnumerator_full) {
                NSString *filePath = [tempFilePath stringByAppendingPathComponent:fileName];
                NSDictionary<NSString *, id> *attrs = [[NSFileManager defaultManager] attributesOfItemAtPath:filePath error:nil];
                size += [attrs fileSize];
            }

获取fullFilePath 用了tempFilePath的前缀沙盒路径，所以有问题

**Comment by newyjp** [comment]
已修改.
