### ISSUE TITLE
请问 pod里面没有 2.3.2版本，是版本号写错了，还是pod没有更新？

### ISSUE THREAD

**Issue by wgbiphone** [newyjp/JPVideoPlayer#70]

**Comment by newyjp** [comment]
![snip20170908_6](https://user-images.githubusercontent.com/14839923/30208790-9af4e69e-94c7-11e7-907b-df32ef929443.png)

**Comment by wgbiphone** [comment]
-> JPVideoPlayer (2.3.1)
   Automatic play video in UITableView like Weibo home page in main thread and
   never block main thread.
   pod 'JPVideoPlayer', '~> 2.3.1'
   - Homepage: https://github.com/Chris-Pan/JPVideoPlayer
   - Source:   https://github.com/Chris-Pan/JPVideoPlayer.git
   - Versions: 2.3.1, 2.3.0, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.2, 2.1.1,
   2.1.0, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.5.0, 1.4.2, 1.4.1, 1.3.1,
   1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.0 [master repo]


我这上传不了图，好像还是没有2.3.2

**Comment by newyjp** [comment]
使用 git help 清除掉缓存, 再重新搜索, git 的使用问题请自行 Google. 谢谢支持.

**Comment by newyjp** [comment]
使用 git help 找到清除索引缓存的命令. git 的使用问题, 请自行 Google. 谢谢支持.

**Comment by wgbiphone** [comment]
谢谢您的解答，我发现可能是我的pod版本太低了，升级后可以了
