### ISSUE TITLE
iPhone6可以正常播放，iPhone5s不能播放

### ISSUE THREAD

**Issue by TGT9499** [newyjp/JPVideoPlayer#73]
iPhone6上运行Demo可以播放，iPhone5s不能播放，还有，问题没有回复能不close吗

**Comment by newyjp** [comment]
你提交的问题没有说我应该怎么重现, 我没有办法帮到你.

**Comment by TGT9499** [comment]
直接使用5s运行Demo，加载不出来视频界面
