### ISSUE TITLE
同志啊，没找到获得视频总时长的api啊

### ISSUE THREAD

**Issue by ghostlordstar** [newyjp/JPVideoPlayer#85]
视频总时长不能获得，我们需要自定义下方的进度条，所以需要总时长和当前时长

**Comment by ChenZhenChun** [comment]
很多api没有开放，其实我觉得一些方法应该使用代理委托出来。这样灵活度高点。目前我是使用下面的方法计算视频的总时长（可以写在视频状态回调中，等视频准备好了就能拿到总时长。目前只有这种方法）：
JPVideoPlayerPlayVideoToolItem *currentPlayVideoItem = [JPVideoPlayerPlayVideoTool sharedTool].currentPlayVideoItem;
        CMTime duration = currentPlayVideoItem.currentPlayerLayer.player.currentItem.asset.duration;
        CGFloat seconds = CMTimeGetSeconds(duration);
        NSString *timeStr = [NSString stringWithFormat:@"%02ld:%02ld:%02ld",(long)seconds/3600,(long)seconds%3600/60,(long)seconds%60];

**Comment by newyjp** [comment]
Try version 3.0 please.
