### ISSUE TITLE
全屏回来之后导航有点问题

### ISSUE THREAD

**Issue by theHeroisBack** [newyjp/JPVideoPlayer#93]
这是没有横屏之前  
![img_2509](https://user-images.githubusercontent.com/30762999/31598429-32df25a2-b280-11e7-9e1d-89eb8c42f34a.PNG)
横屏回来之后导航变成这样了
![img_2510](https://user-images.githubusercontent.com/30762999/31598431-3f7b1bc2-b280-11e7-8ebc-c3f233760c69.PNG)

**Comment by newyjp** [comment]
你改了 Window 的方向了吧?

**Comment by theHeroisBack** [comment]
- (void)doubleTap_action:(UITapGestureRecognizer *)sender {
    if (sender.state == UIGestureRecognizerStateEnded) {
        if (self.bg_view.viewStatus == JPVideoPlayerVideoViewStatusPortrait) {
            [self.bg_view jp_gotoLandscapeAnimated:YES completion:nil];
        }
        else if (self.bg_view.viewStatus == JPVideoPlayerVideoViewStatusLandscape) {
            [self.bg_view jp_gotoPortraitAnimated:YES completion:nil];
        }
    }
}

这是我的双击全屏方法，没改window的方向啊

**Comment by newyjp** [comment]
Try version 3.0 please.
