### ISSUE TITLE
我这怎么清除缓存之后才能播放

### ISSUE THREAD

**Issue by LiberalChen** [newyjp/JPVideoPlayer#94]
第一次可以正常播放，在此播放的时候就playingStatus = 4了，如果把缓存清楚，就可以正常播放了，帮忙看看哪里的问题
![image](https://user-images.githubusercontent.com/19303164/31669746-8981dc74-b31b-11e7-8ab7-5b72aea486e7.png)

**Comment by liudiange** [comment]
这个你你自己的问题 因为他下载好了 你需要点击重新播放才可播放  。

**Comment by LiberalChen** [comment]
@liudiange 不太明白额，可以贴下代码吗？ 我播放完之后，把 self.videoContainer  已经销毁了。怎么重新播放啊？

**Comment by newyjp** [comment]
Try version 3.0 please.
