### ISSUE TITLE
某些连接不能边下边播，只有等完全下完才能播放

### ISSUE THREAD

**Issue by madongdong5550422** [newyjp/JPVideoPlayer#95]
@"http://static.smartisanos.cn/common/video/ammounition-video.mp4",
@"http://static.smartisanos.cn/common/video/proud-driver.mp4",
@"http://static.smartisanos.cn/common/video/proud-farmer.mp4"

这几个连接不能变下边播

**Comment by madongdong5550422** [comment]
这些连接都是你demo中的，帮看一下，现在怀疑codec: isom的视频不能播放。但也不确定

**Comment by newyjp** [comment]
我也一直致力于找解决办法, 从我现在看过的资料来看, 没法在 AVPlayer 实现正真的边下载边播放, 但是不排除 FFmpeg 可以, 接下来我会去尝试使用 FFmpeg, 如果 OK 了, 就写 3.0 版本.
