### ISSUE TITLE
1.请问如果我改变声音大小怎么办？（avplayer是支持改变声音大小的） 

### ISSUE THREAD

**Issue by liudiange** [newyjp/JPVideoPlayer#96]
还有确实没有看到获取视频的总时间的api

**Comment by zszen** [comment]
给你个方法找到这里面的avplayer, 虽然是使用了代理, 但是一样需要avplayer来播放, 很好找到, 只要找到相关的api就可以, 先找到 - (void)setPlayerMute:(BOOL)mute{ 这句
再进入 [[JPVideoPlayerPlayVideoTool sharedTool] setMute:mute];
你就看到了 self.currentPlayVideoItem.player.muted = mute;
其中的.player就是avplayer

添加个公开的
- (void)setVolume:(float)volume{
	self.currentPlayVideoItem.player.volume = volume;
}
或者把player开放给核心就好了

**Comment by newyjp** [comment]
Try version 3.0 please.
